USE sqldb;
CREATE TABLE stdtbl (stdName VARCHAR(10) NOT NULL PRIMARY KEY,
addr CHAR(4) NOT NULL);
CREATE TABLE clubtbl (clubName VARCHAR(10) NOT NULL PRIMARY KEY,
roomNo CHAR(4) NOT NULL);
CREATE TABLE stdclubtbl (num INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
stdName VARCHAR(10) NOT NULL,
clubName VARCHAR(10) NOT NULL,
FOREIGN KEY(stdName) REFERENCES stdtbl(stdName),
FOREIGN KEY(clubName) REFERENCES clubtbl(clubName));